MyAwesomeCart/urls.py
from django.contrib import admin
from django.urls import path, include
#managing media
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls') ),
    path('blog', include('blog.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="blogHome")
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "shop"
urlpatterns = [
    path("", views.index, name="ShopHome"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("tracker", views.tracker, name="TrackingStatus"),
    path("search", views.search, name="Search"),
    path('product/<int:myid>', views.productview, name="productview"),
    path("checkout", views.checkout, name="checkout"),
]

blog/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    desc = models.TextField()
    pub_date = models.DateField()
    img = models.ImageField(upload_to="shop/images", default="")

    def __str__(self):
        return self.product_name


class Contact(models.Model):
    cont_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, default="")
    phone = models.CharField(max_length=70, default="")
    desc = models.TextField()

    def __str__(self):
        return self.name


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=90)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, default="")
    phone = models.CharField(max_length=70, default="")
    address = models.TextField()
    city = models.CharField(max_length=90, default="")
    state = models.CharField(max_length=90,  default="")
    zipcode = models.CharField(max_length=90,  default="")

    def __str__(self):
        return self.name + self.phone


class OrderUpdate(models.Model):
    update_id = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default="")
    update_desc = models.CharField(max_length=5000)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.update_desc[0:7] + '...'

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'blog/index.html')

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from math import ceil
import json
from .models import Product, Contact, Orders, OrderUpdate  # to import all things from database

# Create your views here.


def index(request):
    products = Product.objects.all()  # fetching data from database..
    allProds = []
    # to diffn from category wise and id wise
    catprods = Product.objects.values('category', 'id')
    cats = {item["category"]
            for item in catprods}  # catgeory in set compreehensation
    for cat in cats:
        prod = Product.objects.filter(category=cat)
        n = len(prod)
        # to calculate no of slide and ceil funct comes from math
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        # taking an range func so that i can use value in template func as it return generator
        allProds.append([prod, range(1, nSlides), nSlides])

    params = {'allProds': allProds}  # passing an template with name product
    return render(request, "shop/index.html", params)


def about(request):
    return render(request, "shop/about.html")


def contact(request):
    if request.method=="POST":
        # print(request)
        name=request.POST.get('name', '')
        email=request.POST.get('email', '')
        phone=request.POST.get('phone', '')
        desc=request.POST.get('desc', '')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
    return render(request, "shop/contact.html")

def search(request):
    return render(request, 'shop/search.html')


def productview(request, myid):
    #fetching the product using the id..
    product = Product.objects.filter(id=myid)

    return render(request, 'shop/productview.html', {'product':product[0]})
def checkout(request):
    if request.method=="POST":
        items_json = request.POST.get('itemjson', '')
        name=request.POST.get('name', '')
        email=request.POST.get('email', '')
        phone=request.POST.get('phone', '')
        address=request.POST.get('address', '') + " " + request.POST.get('address2', '')
        city=request.POST.get('city', '')
        state=request.POST.get('state', '')
        zipcode=request.POST.get('zipcode', '')
        order = Orders(items_json=items_json, name=name, email=email, phone=phone, address=address, city=city,state=state, zipcode=zipcode)
        order.save()
        update = OrderUpdate(order_id=order.order_id, update_desc="The order has been placed.")
        update.save()
        thank = True
        id = order.order_id
        return render(request, 'shop/checkout.html', {'thank':thank, 'id': id}) #sending parametre thank and id in script
    return render(request, 'shop/checkout.html')
def tracker(request):
    if request.method=="POST":
        orderid=request.POST.get('orderid', '')
        email=request.POST.get('email', '')
        # return HttpResponse(f"{orderid} and {email}")
        try:
            order = Orders.objects.filter(order_id=orderid, email=email)
            if len(order)>0:
                update = OrderUpdate.objects.filter(order_id=orderid)
                updates = []
                for items in update:
                    #update desc comes from checkout update.

                    #using json below and using json module, but was getting error becoz using item instead of items of json
                    updates.append({'text': items.update_desc, 'time': items.timestamp})
                    #just converting updates and itemsjson from orders
                    response = json.dumps([updates, order[0].items_json], default=str)
                return HttpResponse(response)
            else:
                return HttpResponse("{}")
        except Exception as e:
            return HttpResponse("{}")
    return render(request, 'shop/TrackingStatus.html')

shop/templates/shop/TrackingStatus.html
{% extends 'shop/base.html' %}

{% block title%} Tracking Status {% endblock %}

{% block body %}
<div class="container">
    <div class="col my-4">
        <h2> Enter your order id and Email address to track your orders </h2>
        <form class="row g-3" method="post" action="#" id="trackerform">
            {% csrf_token %}
            <div class="my-4">
                <label for="inputname" class="form-label">order Id</label>
                <input type="text" class="form-control" name="orderid" id="orderid"
                    placeholder="Add your order Id here.">
            </div>
            <div class="my-2">
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>
            <button type="submit" class="btn btn-primary">Track Your Order</button>
    </div>
    <div class="col my-4">
        <h2>Your Order Status</h2>
        <div class="my-4">
            <ul class="list-group" id="items">
                Enter your order Id and Email and click Track Order to find details about your order!
            </ul>
        </div>
    </div>
    <div class="col my-4">
        <h2>Your Order details</h2>
        <div class="my-4">
            <ul class="list-group" id="citems">
            </ul>
        </div>
    </div>
</div>
{% endblock %}
{%block js %}
<script>
    // things to do 
    // have to show updates and when order is gonna come.
    $('#trackerform').submit(function (event) {
        $('#items').empty();
        var formdata = {
            'orderid': $('input[name=orderid]').val(), // hum le aa rahe hai input whose name is orderid
            'email': $('input[name=email]').val(), //hum le aa rahe hai input whose name is email.
            'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
        };
        // starting ajax
        $.ajax({
            type: 'POST',
            url: "{% url 'shop:TrackingStatus'%}",
            data: formdata,
            encode: true
        })
            .done(function (data) {
                // console.log(data)
                data = JSON.parse(data);
                // filling data from 0th index and for 1st index 
                updates = data[0];
                if (updates.length > 0 & updates != {}) {
                    for (i = 0; i < updates.length; i++) {
                        let text = updates[i]['text'];
                        let time = updates[i]['time'];
                        mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                            ${text}
                            <span class="badge bg-primary rounded-pill">${time}</span>
                            </li>` // `` in betn these can u pass  string

                        $('#items').append(mystr);
                    }
                }
                else {
                    mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                            Sorry
                            </li>` // `` in betn these can u pass  string

                    $('#items').append(mystr);
                }
                // fill the order details here
                cart = JSON.parse(data[1]);
                // above we were getting error becoz data[1] is string hence we need to parse
                console.log(cart);
                for (item in cart) {
                    let name = cart[item][1];
                    let qty = cart[item][0];
                    mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    ${name}
                     <span class="badge bg-primary rounded-pill">${qty}</span>
                        </li>` // `` in betn these can u pass  string

                    $('#citems').append(mystr);
                }
            });
        event.preventDefault();
    });
</script>
{% endblock %}

shop/templates/shop/about.html
{% extends 'shop/base.html' %}

{% block title%} About {% endblock %}

{% block body %}
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">My Awesome Cart!</h1>
            <p>My Awesome Cart Pvt Ltd. is an Indian electronic commerce company based in Bengaluru, India. Founded by
                Sachin Bansal and Binny Bansal in 2007, the company initially focused on book sales, before expanding
                into other product categories such as consumer electronics, fashion, and lifestyle products.

                The service competes primarily with Amazon' s Indian subsidiary, and the domestic rival Snapdeal.[5][6]
                as of March 2017, Flipkart held a 39.5% market share of India's e-commerce industry.[7] Flipkart is
                significantly dominant in the sale of apparel (a position that was bolstered by its acquisitions of
                Myntra and Jabong.com), and was described as being "neck and neck" with Amazon in the sale of
                electronics and mobile phones.[8] Flipkart also owns PhonePe, a mobile payments service based on the
                Unified Payments Interface (UPI).

                In August 2018, U.S.-based retail chain Walmart acquired a 77% controlling stake in Flipkart for US$16
                billion, valuing it at $22 billion.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula
                    porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh,
                    ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
            </div>
        </div>

        <hr>

    </div> <!-- /container -->

</main>



{% endblock %}

shop/templates/shop/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'shop/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <title>{% block title%} {% endblock %}</title>
    {% block css %} {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url 'shop:ShopHome'%}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:about'%}">About us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:contact'%}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:TrackingStatus'%}">Track ur shipment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:checkout'%}"> Checkout</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <button type="button" class="btn btn-secondary mx-2" id="popcart" data-container="body"
                    data-toggle="popover" data-placement="left" data-html="true" data-content="">
                    <!-- to change placemnt change data placement from bot to left right up or bottom -->
                    Cart(<span id="cart">0</span>)
                </button>
            </div>
        </div>
    </nav>
    </div>
    {% block body%} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    {% block js %} {% endblock %}

</body>


</html>

shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}

{% block title%} Checkout {% endblock %}

{% block body %}
<div class="container">
    <div class="col my-4">
        <h2> My Awesome Cart Express Checkout - Review Your Cart items </h2>
        <div>
            <ul class="list-group my-4" id='items'>
            </ul>
            <!-- to show total price -->
            <span id="totalprice"></span>
        </div>
    </div>
    <div class="col my-4">
        <h2>step2- Enter address and details: </h2>
        <form class="row g-3" method="post" action="{%url 'shop:checkout' %}">
            {% csrf_token %}
            <!-- here we have used input tag, we were getting error or not getting json id in database becoz of not using of this tag -->
            <input type="hidden" name="itemjson" id="itemjson">
            <div class="col-md-6">
                <label for="Name" class="form-label">Full Name</label>
                <input type="text" class="form-control" name="name" id="name">
            </div>
            <div class="col-md-6">
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>

            <div class="col-12">
                <label for="inputAddress" class="form-label">Address</label>
                <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St">
            </div>
            <div class="col-12">
                <label for="inputAddress2" class="form-label">Address Line 2</label>
                <input type="text" class="form-control" id="address2" name="address2"
                    placeholder="Apartment, studio, or floor">
            </div>
            <div class="col-md-3">
                <label for="Phone" class="form-label">Phone No</label>
                <input type="number" class="form-control" id="Phone" name="phone">
            </div>
            <div class="col-md-3">
                <label for="inputCity" class="form-label">City</label>
                <input type="text" class="form-control" id="city" name="city">
            </div>
            <div class="col-md-4">
                <label for="inputState" class="form-label">Enter State</label>
                <input type="text" class="form-control" id="state" name="state">
            </div>
            <div class="col-md-2">
                <label for="inputZip" class="form-label">Zip</label>
                <input type="text" class="form-control" id="zipcode" name="zipcode">
            </div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Checkout</button>
    </div>
    </form>
</div>
{% endblock %}
{%block js %}
<script>
    if (localStorage.getItem('cart') == null) {
        var cart = {};
    } else {
        cart = JSON.parse(localStorage.getItem('cart'));
    }
    console.log(cart)
    // var sum is given to show total item in cart. 
    var sum = 0;
    var totalprice =0;
    // while python there is f string funct and in JS we have ${} func.
    if ($.isEmptyObject(cart)) {
        mystr = `<p> <b>Your art is empty...</b></p> `
        $('#items').append(mystr);
    }
    else {
        for (item in cart) {
            let name = cart[item][1];
            let qty = cart[item][0];
            let itemprice = cart[item][2];
            sum = sum + qty; // to show quantity of item in cart
            totalprice = totalprice+qty*itemprice;
            mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
            ${name}
            <span class="badge bg-primary rounded-pill">${qty}</span>
                </li>` // `` in betn these can u pass  string

            $('#items').append(mystr);
        }

    }
    document.getElementById('cart').innerHTML = sum;
    document.getElementById('totalprice').innerHTML = totalprice;
    // from here we are taking these items to our database.
    $('#itemjson').val(JSON.stringify(cart));
    {% if thank %}
    alert('Thanks for ordering with us. Your order is is {{id}}. Use it to track your order using our order tracker');
    localStorage.clear();
    document.location = "/";
    {% endif %}
</script>
{% endblock %}

shop/templates/shop/contact.html
{% extends 'shop/base.html' %}

{% block title%} Contact {% endblock %}

{% block body %}
<form action="{% url 'shop:contact'%}" method="post">{% csrf_token %}
    <div class="container">
        <div class="mb-3 my-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" placeholder="Enter Your Name" name="name" id ="name">
        </div>
        <div class="mb-3 my-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" class="form-control" aria-describedby="emailHelp"  name="email" id="email">
            <div class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3 my-3">
            <label for="phoneno" class="form-label"> Phone No.</label>
            <input type="phone" class="form-control"  placeholder="Enter Your Phone No." name="phone" id="phone">
        </div>
        <div class="mb-3 my-3">
            <label for="desc" class="form-label"> describe your issue</label>
            <input type="text" class="form-control" placeholder="Post your issue..." name="desc" id="desc"
            >
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block title%} Home{% endblock %}
<!--        carousel indicators starts from here-->
{%load static%}

{% block css %}
<style>
  /* index.html css */
  .col-md-3 {
    display: inline-block;
    margin-left: -4px;
    max-height: 20%;
  }

  .carousel-indicators .active {
    background-color: blue;
  }

  .col-md-3 img {

    width: 227px;
    height: 242px;
  }

  body .carousel-indicator li {
    background-color: blue;
  }

  body .carousel-indicators {
    bottom: 0;
  }

  body .carousel-control-prev-icon,
  body .carousel-control-next-icon {
    background-color: blue;
  }

  .carousel-control-prev,
  .carousel-control-next {
    top: auto;
    bottom: auto;
    padding-top: 350px;
  }

  body .no-padding {
    padding-left: 0,

  }
</style>

{% endblock %}

{% block body%}

<div class="container">

  <!--Slideshow starts here -->
  {% for product, range, nSlides in allProds %}
  <h5 class="my-4">Flash Sale On {{product.0.category}} - Recommended Items</h5>
  <div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
      <ul class="carousel-indicators">
        <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

        {% for i in range %}
        <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
        {% endfor %}
      </ul>


      <div class="container carousel-inner no-padding">

        <div class="carousel-item active">


          {% for i in product %}
          <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="card" style="width: 18rem;">
              <img src='/media/{{i.img}}' class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title" id="namepr{{i.id}}">{{i.product_name}}</h5>
                <h6 class="card-title">Rs. <span  id="pricepr{{i.id}}">{{i.price}}</span></h6>
                <p class="card-text">{{i.desc | slice:"0:53"}}...</p>
                <!-- container is expanding becoz of desc we need to use trunicate...3 -->
                <span id="divpr{{i.id}}" class="divpr">
                  <button id="pr{{i.id}}" class="btn btn-primary cart">Add To Cart</button>
                </span>
                <a href="{% url 'shop:productview' i.id %}"><button id="qv{{i.id}}" class="btn btn-primary cart">Quick
                    View</button></a>
                </span>
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:3 and forloop.counter > 0 and not forloop.last %}
        </div>
        <div class="carousel-item">
          {% endif %}

          {% endfor %}
        </div>



      </div>
    </div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

{% block js %}
<script>
  // Find out the cart items from localStorage
  if (localStorage.getItem('cart') == null) {
      var cart = {};
  } else {
      cart = JSON.parse(localStorage.getItem('cart'));
      updateCart(cart);
  }
  // If the add to cart button is clicked, add/increment the item
  //$('.cart').click(function() {
      $('.divpr').on('click', 'button.cart', function(){
      var idstr = this.id.toString();
      if (cart[idstr] != undefined) {
      
        qty = cart[idstr][0] + 1;
      } else {
          // for adding in checkout page gona fetch with name hencing adding these..
        qty = 1;
        name = document.getElementById('name'+idstr).innerHTML;
        price = document.getElementById('price'+idstr).innerHTML;
          cart[idstr] = [qty, name,parseInt(price)];
      }
      updateCart(cart);
  });
  //Add Popover to cart
  $('#popcart').popover();
  updatePopover(cart);
  function updatePopover(cart) {
      console.log('We are inside updatePopover');
      var popStr = "";
      popStr = popStr + "<h5> Cart for your items in my shopping cart </h5><div class='mx-2 my-2'>";
      var i = 1;
      for (var item in cart) {
          popStr = popStr + "<b>" + i + "</b>. ";
          popStr = popStr + document.getElementById('name' + item).innerHTML.slice(0, 19) + "... Qty: " + cart[item][0] + '<br>';
          i = i + 1;
      }
      popStr = popStr + "</div> <a href='{%url 'shop:checkout'%}'><button class='btn btn-primary' id ='checkout'>Checkout</button></a> <button class='btn btn-primary' onclick='clearCart()' id ='clearCart'>Clear Cart</button>     "
      console.log(popStr);
      document.getElementById('popcart').setAttribute('data-content', popStr);
      $('#popcart').popover('show');
  }
  function clearCart() {
      cart = JSON.parse(localStorage.getItem('cart'));
      for (var item in cart) {
          document.getElementById('div' + item).innerHTML = '<button id="' + item + '" class="btn btn-primary cart">Add To Cart</button>'
      }
      localStorage.clear();
      cart = {};
      updateCart(cart);
  }
  function updateCart(cart) {
      var sum = 0;
      for (var item in cart) {
          sum = sum + cart[item][0];
          document.getElementById('div' + item).innerHTML = "<button id='minus" + item + "' class='btn btn-primary minus'>-</button> <span id='val" + item + "''>" + cart[item][0] + "</span> <button id='plus" + item + "' class='btn btn-primary plus'> + </button>";
      }
      localStorage.setItem('cart', JSON.stringify(cart));
      document.getElementById('cart').innerHTML = sum;
      console.log(cart);
      updatePopover(cart);
  }
  // If plus or minus button is clicked, change the cart as well as the display value
  $('.divpr').on("click", "button.minus", function() {
      a = this.id.slice(7, );
      cart['pr' + a][0] = cart['pr' + a][0] - 1;
      cart['pr' + a][0] = Math.max(0, cart['pr' + a][0]);
      document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
      updateCart(cart);
  });
  $('.divpr').on("click", "button.plus", function() {
      a = this.id.slice(6, );
      cart['pr' + a][0] = cart['pr' + a][0] + 1;
      document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
      updateCart(cart);
  });
  </script>
{% endblock %}

shop/templates/shop/productview.html
{% extends 'shop/base.html' %}

{% block title%} {{product.product_name}} {% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                <img src="/media/{{product.img}}" alt="">
            </div>
            <div class="row">
                <button class="btn btn-primary">Buy Now</button>
                <button class="btn btn-primary">Add to Cart</button>
            </div>
        </div>
        <div class="col-md-8">
            <h5>
                {{product.product_name}}
            </h5>
            <p><b>
                {{product.price}}
            </b></p>
            <p>
                {{product.desc}}
            </p>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
console.log('working');
if(localStorage.getItem('cart') == null){
var cart = {};
}
else
{
cart = JSON.parse(localStorage.getItem('cart'));
document.getElementById('cart').innerHTML = Object.keys(cart).length;
}
$('.cart').click(function(){
console.log('clicked');
var idstr = this.id.toString();
console.log(idstr);
if (cart[idstr] !=undefined){
cart[idstr] = cart[idstr] + 1;
}
else
{
cart[idstr] = 1;
}
console.log(cart);
localStorage.setItem('cart', JSON.stringify(cart));
document.getElementById('cart').innerHTML = Object.keys(cart).length;
});
$('#popcart').popover();
document.getElementById("popcart").setAttribute('data-content', '<h5>Cart for your items in my shopping cart</h5>');
</script>
{% endblock %}

shop/templates/shop/search.html
% extends 'shop/base.html' %}

{% block title%} search{% endblock %}
<!--        carousel indicators starts from here-->
{%load static%}